#!/bin/bash
echo "All variables: $@"
echo "Number of variables passed: $#"
echo "Script name: $0"
echo "Current working directory: $PWD"
echo "Home directory of current user: $HOME"
echo "Which user running the script: $USER"
echo "Host name of the server: $HOSTNAME"
echo "Process ID of current shell script: $$"
sleep 60 &
echo "Process ID of last background command: $!"
